# Generated by Django 3.2.5 on 2021-08-15 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema_example_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emailAddress',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_schema_example_app.user'),
        ),
    ]
